### ISSUE TITLE
Implement image upload from computer

### ISSUE THREAD

**Issue by ckhorra1** [COSC481W-2022Winter/capstone-hackmcx#106]
As a fellow web surfer I want to easily be able to upload an image from my computer and use it to create a post, as well as update my own profile picture.

**Acceptance Criteria:**

- Create Post page includes an image button to upload an image. Once clicked it will open up the users own finder/file explorer where they will be able to choose any photo they have.
- On a successful upload under the image upload button , the name of the file will be displayed.
- Replace imageUrl textfield with image upload button.
- Notify user if the file size or type is invalid.
- Have the same exact option to upload an image , but for user profile page, when changing the profile picture.

**Tasks:**
- [x] Create image upload button on create post, where the user will be able to pick a file to upload from their computer. (Ari and Cyrus)
- [x] File name gets displayed under upload image button after successful file upload. (Cyrus and Ari)
- [x]  Replace the image url textfield with the image upload button.. (Ari and Cyrus)
- [x] Update the post request to use an image and not an image url.(Cyrus and Ari)
- [x] Handle invalid file size or type, and notify the user.(Ari and Cyrus).
- [x] Make an option to upload an image when editing the user profile page.(Ari and Cyrus)
