### ISSUE TITLE
Implement Account Creation Page

### ISSUE THREAD

**Issue by toxictortoise** [COSC481W-2022Winter/capstone-hackmcx#107]
As a web surfer I want to be able to make an account in order to access all of the sites features.

**Acceptance Criteria:**

- Login page has a link to the account creation page
- When a user is redirected to the account creation page, they are presented with the logo, a submit button, and text boxes for: username, password, first name, last name, and re-type password.
- The account creation page gives a warning if the username or password are invalid. The username or password are invalid if they are empty or the password is too weak
- The account creation page displays a message explaining the issue if account creation fails
- If account creation succeeds the account creation page redirects to the login page

**Tasks:**
- [x] Create "Create Account Page" react component /Wyatt
- [x] Add button to login page that redirects to the create account page /Wyatt
- [x] Component displays logo at the top of the page /Wyatt
- [x] Component has text fields for first name, last name, username, password, and retype password. /Wyatt
- [x] If account creation succeeds redirect to the login page /Ehtesham
- [x] Disable the submit button if the username or password are blank or the password is too weak /Ehtesham
