### ISSUE TITLE
Setup Database Migration

### ISSUE THREAD

**Issue by 3dxp** [COSC481W-2022Winter/capstone-hackmcx#11]
As a developer I want my database to stay in sync with the code base I am working on.

Acceptance Criteria:
- When a developer runs the API application with the "--migrate" flag the database schema is synced with the migrations defined in that code revision. 
- When a developer runs the API application with the "--seed" flag the database is seeded with a test data set defined in the app.

**Task List:**
- [x] Replace meriadb lib with Knex JS /Connor
- [x] Setup app to run migrations when a "--migrate" flag is provided /Kevin
- [x] Setup app to run seed data when a "--seed" flag is provided. /Alec

**Comment by 3dxp** [comment]
We ran into an issue with Knex that requires all migrations and seed data operations to be written in common JS to work on other platforms. This caused some weird delays as things worked fine on linux without the changes. Yay cross-platform compatibility!
