### ISSUE TITLE
Implements Update Password Endpoint Action

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#16]
As a business user I want to persist user login data securely so that in the future the account can be updated or deactivated.

**Tasks:**

- [ ] Create Accounts table  /Alec
- [ ] Add migration and seed for Accounts table   /Kevin
- [ ] Update POST endpoint /v1/users to create both Account and User entry   /Connor
- [ ] Create POST endpoint /v1/users/{userId}/_updatePassword to update password for Accounts table  /Alec

**Acceptance Criteria:**

- When a POST request is made against the /v1/users/{userId}/_updatePassword endpoint with a JSON request body with a password. A response with a 201 response code is returned to the client.
- When an invalid POST request is made against the /v1/users/{userId}/_updatePassword endpoint an error code is returned. (In the 400-499 HTTP response code.)
