### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by ahassani93** [COSC481W-2022Winter/capstone-hackmcx#18]
As a fellow web surfer I want a quick icon/way to identify the website I am viewing, so I know where I am and what I'm interacting with. 

**Acceptance Criteria:**
- When the application is loaded the icon / logo is set as the fav-icon. 
- When a user sees the logo it is identifiable and unique.
- When a user has light or dark themed applications the logo is still easy to identify.
- The icon should appear on the browser tab.

**Task List:**
- [x] Create logo concepts for group to vote on.
- [x] Get second round of feedback on approved logo concept.
- [x] Prepare logo for exports. (Make sure it is transparent and resizable.)
- [x] Add logo as fav-icon

**Comment by ahassani93** [comment]
![Logo_Final_Transparent](https://user-images.githubusercontent.com/60075993/153519690-4bc2f6db-bfe8-4834-8503-af8769631890.png)

**Comment by sjiang1** [comment]
Add an acceptance criterion:
* The icon should appear on the browser tab.

**Comment by sjiang1** [comment]
Missing a task list. I guess it's because the issue was about only creating a logo. So there's no task list. Please make sure to satisfy the new acceptance criterion.
