### ISSUE TITLE
Implement GET v1/posts endpoint

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#22]
As a business user I want to persist post data so that I can retrieve it later for future use.

**Acceptance Criteria:**
- When a GET request is made against the /v1/posts endpoint a JSON document is returned with a collection of objects with the post title, id, and image url. 
- When an invalid GET request is made against the /v1/posts endpoint an error code is returned. (In the 400-499 HTTP response code.)

**Tasks:**
- [x] Create posts model. (Cancelled)
- [x] Create posts table.
- [x] Create controller for getting posts.
- [x] Create the route for GET /v1/posts

**Comment by 3dxp** [comment]
We have not yet implemented a model for posts to simplify the initial implementation of the endpoints. 

If things get more complicated we may move to an ORM or build resource repositories.
