### ISSUE TITLE
Implement individual Post page

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#44]
As a fellow web surfer I want to be able to click in on each post to see all captions created for that post, so that I can find the best joke for the post.

**Acceptance Criteria:**
- When the user clicks on a post it redirects to the individual post page
- The page displays a list of captions for the post
- The page displays the individual post and title

**Tasks:**
- [x]  Create individual post page /Wyatt
- [x]  Post component is displayed at the top-middle of the screen /Wyatt
- [x]  list of caption components displayed in a vertical column in the middle of the screen if captions are present in the API. /Wyatt
     - [x] When the page first loads make a request to the GET /v1/posts/captions endpoint /Ehtesham
