### ISSUE TITLE
Implement user login page and update user info

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#45]
As a account holder I want to be able to login with my credentials to have access to the sites functionality so that I can create with Posts and Captions.

**Acceptance Criteria:**
- When a user is redirected to the login page, they are presented with the logo, the username and password text boxes, as well as a submit button.
- The login page gives a warning if the username or password are invalid. The username or password are invalid if they are empty or the password is too weak
- The login page displays a message explaining the issue if login fails
- If login succeeds the login page redirects to the landing page

**Tasks:**
- [x] Create "Login Page" react component /Wyatt
- [x] Component displays logo at top of page /Wyatt
- [x] Component has a text field for username /Ehtesham
- [x] Component has a text field for password /Ehtesham
- [x] Component has a button for login /Ehtesham
- [x] If already signed in redirect to “homepage” /Ehtesham
- [x] Connect the update profile page to the new API endpoint /Ehtesham

**Comment by sjiang1** [comment]
This user story needs to have the function of login. Or, you don't need to do it at all.

**Comment by sjiang1** [comment]
Missing a few important acceptance criteria:

1. the login page should give a warning if the username or password are invalid (empty or password too weak)
2. the login page should also give a login fail message if login fails
3. if login succeed, the login page should be redirected to …
