### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by acampb65** [COSC481W-2022Winter/capstone-hackmcx#47]
As a content creator, I want a place where all of my taglines and photos can be viewed by myself and others so that I can reflect on how funny I am and how funny others think I am.

**Acceptance Criteria:**
- The user information (username, first name, last name) are visible on the page.
- Other visitors to the page can view profile photo.
- The user is able to upload and update the profile picture of their account.

**Tasks:**
- [x] Page layout creation /Wyatt
- [x] GET the user information from the API and display it /Wyatt
- [x] Profile photo upload form component /Ehtesham

**Comment by zxkevin** [comment]
Sub issues:
#61 #62

**Comment by acampb65** [comment]
AC Change: "The user information (username, number of posts) are visible on the page." and "Other visitors to the page can view the user's posts, profile photo and rating."

Updated to: "The user information (username, first name, last name) are visible on the page." and "Other visitors to the page can view the user's profile photo."

We would like to remove user posts and ratings, that functionality was meant for a future sprint.
