### ISSUE TITLE
Implement Caption creation component

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#48]
As an account holder I want a page for creating a Caption for each Post, so that others can see my funny caption for the image.

**Acceptance Criteria:**
- Text fields for each specific post as well as button for submission.
- When a user clicks on the submit button whatever they typed in the captions box will be uploaded. Currently, users can submit captions anonymously.
- Create the Caption creation component.

**Tasks:**
- [x] Create a Create captions component. /Cyrus
- [x] Create a textfield and submission button for each post. /Cyrus & Ari
- [x] Page gives a response if the caption got submitted successfully after the submission button is clicked. /Cyrus & Ari
- [x] Display the image of the post being captioned at the top of the page. /Ari

**Comment by sjiang1** [comment]
Can you submit a caption without login? What happens if a user submits without login? Please add this to your acceptance criteria.

**Comment by 3dxp** [comment]
Currently users of the site will be able to submit captions on posts anonymously.

**Comment by ahassani93** [comment]
Updated the acceptance criteria to include a note on caption creation without login.

**Comment by ahassani93** [comment]
Changed "page" to "component" because of duplicate tasks with issue #44.
