### ISSUE TITLE
Validate Input Fields for Post Submission

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#54]
As a content creator I want to be able to know if the values I input for upload is valid as I enter them so that I can create posts accurately.

**Acceptance Criteria:**
- Checks for empty/null input on captions and create post.
- Checks for invalid URL on image field of create post.
- If a user inputs improperly formatted information on the create post page they will be prevented from submitting the form.
- If a user inputs improperly formatted information and attempts to submit, then the problem will be explained and visually indicated via the text fields.

**Tasks:**
- [x] Required fields are shown in red if attempting to submit empty /Wyatt
- [x] Display warning/error message /Wyatt
- [x] Empty/null fields cannot be submitted /Wyatt
- [x] Invalid URLs cannot be submitted on create post /Wyatt

**Comment by sjiang1** [comment]
" I **can can** create posts accurately. "

Can you give me a few examples of "improperly formatted information on the create post page"?

**Comment by acampb65** [comment]
Fixed the duplicate "can" in user story. Updated tasks and acceptance criteria to include examples of improperly formatted information.
