### ISSUE TITLE
Implement Rating Selector for Captions

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#55]
As a fellow web surfer I want a convenient place to give rating to each Caption for each Post so that I can voice my opinion on how good each Caption is.

**Acceptance Criteria:**
- When the user loads a post a there will be a five star scale where the user can rate the caption.
- When the user selects a rating there will be hover feedback that will display a label when hovered to help the user pick the correct rating value
- When a user clicks on the star to submit the feedback they will get a response from the website indicating that the feedback has been submitted successfully or not.

**Tasks:**
- [x] Create a rating system with the correct amount of stars. /Cyrus
- [x] Implement hover feature where you can see the rating before you submit it. /Cyrus & Ari
- [x] Clicking star value performs POST request to API containing the rating. /Ari

**Comment by sjiang1** [comment]
This user story is closely related to #59 
You can keep them separated. They will be considered as one in review and they need to work together.
