### ISSUE TITLE
Updated database for Uploading Images

### ISSUE THREAD

**Issue by acampb65** [COSC481W-2022Winter/capstone-hackmcx#6]
As a content creator, I want to upload images to the website from my computer so that I can post my own work for everyone to see.

**Tasks:**

- [ ] Update post table to store Images base64  /Kevin
- [ ] Update user table to store Images base64  /Connor
- [ ] Update seed and migration for post table and user table  /Alec

**Acceptance Criteria:**

- When a request is made against the POST endpoints for posts/users it is updated to handle and store images.
- When an unauthenticated request is made against an endpoints, an error code 401 is returned.

**Comment by 3dxp** [comment]
I don't think we have to update the users or posts table for images, we would just use a URL that points to our image hosting. So if an image is not uploaded we can still reference other images. This will require some work with the front-end to make sure the local image URLs we return work as expected.
