### ISSUE TITLE
Implement GET /v1/users Endpoint

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#61]
As a business user I want to persist user data so that I can retrieve it later for future use, so that the website will be up to date.

**Tasks:**

- [x] Create controller for getting users
- [x] Create the route for GET /v1/users
- [x] Create the route for GET /v1/users/{id}

**Acceptance Criteria:**
- When a GET request is made against the /v1/users endpoint a JSON document is returned with a collection of objects with the first name, last name, and username.
- When an invalid GET request is made against the /v1/users endpoint an error code is returned. (In the 400-499 HTTP response code.)

**Comment by sjiang1** [comment]
"Create users table" task is already in #62

**Comment by zxkevin** [comment]
I have removed "Create users table" from both #62 and #61 (this issue) because the task is a part of #60
