### ISSUE TITLE
Create a "Post" React Component

### ISSUE THREAD

**Issue by acampb65** [COSC481W-2022Winter/capstone-hackmcx#63]
As a developer I want to define what a post is in one file so that I only have to make changes to said file rather than all files where posts are applicable which speeds up development and reduces problems.

**Acceptance Criteria:**
- The landing page should look the same as it did previously.
- PostList.js should render the new Post component
- Post.js is located in /packages/hackmcx-client/src/components/

**Tasks:**
- [x] Copy "post" code from PostList.js into new Post.js component /Ehtesham
- [x] Component can be passed data for image, caption, and rating /Ehtesham
- [x] Component displays post image /Ehtesham
- [x] Component displays post caption /Ehtesham
- [x] Replace "post" code in PostList.js with new Post component /Ehtesham
