### ISSUE TITLE
Separate User login info and User bio info

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#84]
As a business user I want to persist user login data and user info into separately so that in the future each can be updated separately.

**Tasks:**

- [ ] Update POST Login endpoint to query Accounts table  /Kevin
- [ ] Update Users table to remove password  /Connor
- [ ] Update PUT endpoint for Users table  /Alec

**Acceptance Criteria:**

- When a PUT request is made against the /v1/users/{userId} endpoint with a JSON request body with a first name, last name, username, and Account info. A response with the location header set with the relative URL of the created user with a success status code is returned to the client.
- When an invalid PUT request is made against the /v1/users/{userId} endpoint an error code is returned. (In the 400-499 HTTP response code.)
