### ISSUE TITLE
Implement Login Authentication to POST Endpoints

### ISSUE THREAD

**Issue by zxkevin** [COSC481W-2022Winter/capstone-hackmcx#87]
As a account holder, I want my login to be safe and secure so that my information doesn't get stolen.

**Tasks:**
- [x] Create PUT /user/{userId} for User update [Kevin, Alec]
- [x] Add Authentication to POST post endpoints [Kevin]
- [x] Add Authentication to POST caption endpoints [Alec]
- [x] Add Authentication to POST _rating endpoints [3dxp]
- [x] Add Authentication middleware... [3dxp]

**Acceptance Criteria:**
- When a request is made against the POST endpoints for posts it is authenticated. 
- When an unauthenticated request is made against an endpoints, an error code 401 is returned.
- Unauthenticated Users can still view site content.
