### ISSUE TITLE
Update frontend login functionality

### ISSUE THREAD

**Issue by toxictortoise** [COSC481W-2022Winter/capstone-hackmcx#88]
As a user that wants to see posts by users that I find funny, I want all captions, posts, and ratings to be attached to a user. 

**Acceptance Criteria:**
- If a user is logged in, there is a link to their user profile on the navbar. If no user is logged in there is a login button
- If a user isn't logged in, they cannot make posts, create captions, or rate captions

**Tasks:**
- [ ] add a profile button to the navbar that links to the user page. If user isn't logged in, the button is replaced by a sign in button
- [ ] If no user is logged in remove the create caption component from the individual post page
- [ ] If no user is logged in remove the create post button from navbar
- [ ] If no user is logged in disable the onChange function of Ratings
- [ ] Handle 401 not authorized errors
