### ISSUE TITLE
Update frontend login functionality

### ISSUE THREAD

**Issue by toxictortoise** [COSC481W-2022Winter/capstone-hackmcx#89]
As a user, I want to see the available options that I have if I am logged in, and see what I am missing out on if I am not logged in.

**Acceptance Criteria:**
- If a user is logged in, there is a link to their user profile on the navbar. If the user is logged in there is a login button
- If a user isn't logged in, they cannot make posts, create captions, or rate captions

**Tasks:**
- [x] add a profile button to the navbar that links to the user page. If user isn't logged in, the button is replaced by a sign in button /Cyrus & Ari
- [x] If no user is logged in remove the create caption component from the individual post page /Cyrus & Ari
- [x] If no user is logged in remove the create post button from navbar /Cyrus & Ari
- [x] If no user is logged in disable the onChange function of Ratings /Cyrus & Ari
- [x] Handle 401 not authorized errors /Cyrus & Ari

**Comment by sjiang1** [comment]
The user story and the acceptance criteria don't match.

**Comment by ckhorra1** [comment]
Updated the user story so it better reflects the AC!
